# Use the official Node.js image as the base image for backend
FROM node:20.0.0-alpine AS backend

# Set the working directory for backend
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy backend source code
COPY quirknotes/backend ./

# # Build backend
# RUN npm run dev 

# Expose port 4000 for the application
EXPOSE 4000/tcp

# Command to start the Node.js application
CMD ["node", "server.js"]
