services:
  frontend:
    image: asadcoder/quirknotes_frontend:latest
    ports:
      - "3000:3000"
  backend:
    image: asadcoder/quirknotes_backend:latest
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017" 