name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ahonanhin }}
          password: ${{ secrets.dckr_pat_FSJlwQfl0K6u6NrOOFkTHlb0LLc }}

      - name: Build Docker image
        run: docker build -t ${{ secret.ahonanhin }}/quirknotes_frontend:latest -f Dockerfile_frontend .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ ahonanhin.ahonanhin }}/quirknotes_frontend:latest
